steps:
- name: eu.gcr.io/${PROJECT_ID}/jekyll-cloud-builder:latest
- name: gcr.io/cloud-builders/gcloud
  entrypoint: gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./_site", "gs://gcstatic.gordonmleigh.uk"]